version: '3'
services:
  api:
    build: .
    container_name: django_api
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      sh -c "python application/manage.py migrate &&
             python application/manage.py runserver 0.0.0.0:8000"
            
    depends_on:
      - postgres
      - redis
  celery_worker:
    build:
      context: .
    command: celery --workdir ./application -A app worker -l info
    env_file:
      - .env.docker
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
  postgres:
    image: postgres:12.3
    restart: always
    env_file:
      - .env.docker
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_for_celery
    env_file:
      - .env.docker
    volumes:
      - ./.data/redis:/data
  