version: "3"
services:
  postgres:
    image: postgres:12.3
    restart: always
    env_file:
      - .env
    ports:
      - 5443:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis.dev
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data